// VCAA curriculum descriptors for the Parris Study Platform.
// Source: victoriancurriculum.vcaa.vic.edu.au + vcaa.vic.edu.au VCE study designs.
// Hand-curated v1. Keywords drive keyword-based retrieval in lib/curriculum/retrieve.ts.

export type DescriptorSeed = {
  code: string;
  subject: string;
  yearLevel: string;
  strand: string;
  substrand?: string;
  text: string;
  keywords: string[];
  bloom?: string;
};

export const DESCRIPTORS: DescriptorSeed[] = [
  // === YEAR 10 MATHEMATICS (subject=math10) ===
  { code: 'VCMNA327', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Real numbers', text: 'Solve simple problems involving inverse proportion.', keywords: ['inverse', 'proportion', 'ratio', 'rate', 'variation'], bloom: 'Apply' },
  { code: 'VCMNA329', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Patterns and algebra', text: 'Factorise algebraic expressions including monic and non-monic quadratic expressions.', keywords: ['factorise', 'factor', 'algebra', 'quadratic', 'monic', 'non-monic', 'expression'], bloom: 'Apply' },
  { code: 'VCMNA330', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Linear and non-linear relationships', text: 'Solve problems involving linear equations, including those derived from formulas.', keywords: ['linear', 'equation', 'solve', 'formula', 'algebra', 'substitution'], bloom: 'Apply' },
  { code: 'VCMNA331', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Linear and non-linear relationships', text: 'Solve linear inequalities and graph their solutions on a number line.', keywords: ['inequality', 'inequalities', 'number line', 'linear', 'graph'], bloom: 'Apply' },
  { code: 'VCMNA332', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Linear and non-linear relationships', text: 'Solve linear simultaneous equations using algebraic and graphical techniques including the use of digital technology.', keywords: ['simultaneous', 'equations', 'linear', 'graph', 'intersection', 'elimination', 'substitution'], bloom: 'Apply' },
  { code: 'VCMNA334', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Linear and non-linear relationships', text: 'Explore the connection between algebraic and graphical representations of relations such as simple quadratic, reciprocal, circle and exponential, using digital technology as appropriate.', keywords: ['quadratic', 'reciprocal', 'circle', 'exponential', 'graph', 'parabola', 'function'], bloom: 'Analyse' },
  { code: 'VCMNA335', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Linear and non-linear relationships', text: 'Solve linear equations involving simple algebraic fractions.', keywords: ['algebraic', 'fractions', 'linear', 'equation', 'denominator'], bloom: 'Apply' },
  { code: 'VCMNA336', subject: 'math10', yearLevel: 'Year 10', strand: 'Number and Algebra', substrand: 'Linear and non-linear relationships', text: 'Solve simple quadratic equations using a range of strategies.', keywords: ['quadratic', 'equation', 'factorise', 'quadratic formula', 'completing the square', 'roots'], bloom: 'Apply' },
  { code: 'VCMMG343', subject: 'math10', yearLevel: 'Year 10', strand: 'Measurement and Geometry', substrand: 'Using units of measurement', text: 'Solve problems involving surface area and volume for a range of prisms, cylinders and composite solids.', keywords: ['surface area', 'volume', 'prism', 'cylinder', 'composite', 'solid', '3d'], bloom: 'Apply' },
  { code: 'VCMMG344', subject: 'math10', yearLevel: 'Year 10', strand: 'Measurement and Geometry', substrand: 'Geometric reasoning', text: 'Formulate proofs involving congruent triangles and angle properties.', keywords: ['proof', 'congruent', 'triangle', 'angle', 'geometry', 'reasoning'], bloom: 'Analyse' },
  // === YEAR 10 ENGLISH (subject=english10) ===
  { code: 'VCELY466', subject: 'english10', yearLevel: 'Year 10', strand: 'Reading and Viewing', substrand: 'Texts in context', text: 'Analyse and evaluate how people, cultures, places, events, objects and concepts are represented in texts through language, structural and visual choices.', keywords: ['analyse', 'represent', 'text', 'culture', 'bias', 'perspective', 'viewpoint'], bloom: 'Evaluate' },
  { code: 'VCELA472', subject: 'english10', yearLevel: 'Year 10', strand: 'Reading and Viewing', substrand: 'Expressing and developing ideas', text: 'Analyse and evaluate the effectiveness of a wide range of sentence and clause structures as authors design and craft texts.', keywords: ['sentence', 'clause', 'syntax', 'grammar', 'craft', 'effect'], bloom: 'Evaluate' },
  { code: 'VCELA473', subject: 'english10', yearLevel: 'Year 10', strand: 'Reading and Viewing', substrand: 'Expressing and developing ideas', text: 'Analyse how higher order concepts are developed in complex texts through language features including nominalisation, clause combinations, technicality and abstraction.', keywords: ['nominalisation', 'abstraction', 'technicality', 'clause', 'complex text', 'academic'], bloom: 'Analyse' },
  { code: 'VCELA474', subject: 'english10', yearLevel: 'Year 10', strand: 'Reading and Viewing', substrand: 'Expressing and developing ideas', text: 'Refine vocabulary choices to discriminate between shades of meaning, with deliberate attention to the effect on audiences.', keywords: ['vocabulary', 'word choice', 'connotation', 'audience', 'tone'], bloom: 'Apply' },
  { code: 'VCELT475', subject: 'english10', yearLevel: 'Year 10', strand: 'Literature', substrand: 'Literature and context', text: 'Compare and evaluate a range of representations of individuals and groups in different historical, social and cultural contexts.', keywords: ['literature', 'context', 'historical', 'cultural', 'representation', 'comparison'], bloom: 'Evaluate' },
  { code: 'VCELT479', subject: 'english10', yearLevel: 'Year 10', strand: 'Literature', substrand: 'Examining literature', text: 'Identify, explain and discuss how narrative viewpoint, structure, characterisation and devices including analogy and satire shape different interpretations and responses to a text.', keywords: ['narrative', 'viewpoint', 'characterisation', 'satire', 'analogy', 'interpretation'], bloom: 'Analyse' },
  { code: 'VCELY478', subject: 'english10', yearLevel: 'Year 10', strand: 'Writing', substrand: 'Creating texts', text: 'Create sustained texts, including texts that combine specific digital or media content, for imaginative, informative, or persuasive purposes that reflect upon challenging and complex issues.', keywords: ['writing', 'compose', 'persuasive', 'informative', 'imaginative', 'essay'], bloom: 'Create' },
  { code: 'VCELY480', subject: 'english10', yearLevel: 'Year 10', strand: 'Writing', substrand: 'Editing', text: 'Review, edit and refine students\u2019 own and others\u2019 texts for control of content, organisation, sentence structure, vocabulary, and/or visual features to achieve particular purposes and effects.', keywords: ['edit', 'redraft', 'revision', 'feedback', 'organisation'], bloom: 'Evaluate' },
  // === YEAR 10 SCIENCE (subject=science10) ===
  { code: 'VCSSU122', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Chemical sciences', text: 'All matter is made of atoms which are composed of protons, neutrons and electrons; natural radioactivity arises from the decay of nuclei in atoms.', keywords: ['atom', 'proton', 'neutron', 'electron', 'radioactivity', 'nucleus', 'decay'], bloom: 'Understand' },
  { code: 'VCSSU123', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Chemical sciences', text: 'The atomic structure and properties of elements are used to organise them in the periodic table.', keywords: ['periodic table', 'element', 'atomic', 'group', 'period', 'electron configuration'], bloom: 'Understand' },
  { code: 'VCSSU124', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Chemical sciences', text: 'Different types of chemical reactions are used to produce a range of products and can occur at different rates; chemical reactions may be represented by balanced chemical equations.', keywords: ['chemical reaction', 'balanced equation', 'reaction rate', 'reactant', 'product', 'catalyst'], bloom: 'Apply' },
  { code: 'VCSSU128', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Biological sciences', text: 'The transmission of heritable characteristics from one generation to the next involves DNA and genes.', keywords: ['DNA', 'gene', 'inheritance', 'heritable', 'allele', 'genotype', 'phenotype'], bloom: 'Understand' },
  { code: 'VCSSU129', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Biological sciences', text: 'The theory of evolution by natural selection explains the diversity of living things and is supported by a range of scientific evidence.', keywords: ['evolution', 'natural selection', 'species', 'adaptation', 'fossil', 'evidence'], bloom: 'Evaluate' },
  { code: 'VCSSU131', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Earth and space sciences', text: 'Global systems including the carbon cycle rely on interactions involving the biosphere, lithosphere, hydrosphere and atmosphere.', keywords: ['carbon cycle', 'biosphere', 'atmosphere', 'climate', 'global', 'earth system'], bloom: 'Analyse' },
  { code: 'VCSSU133', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Physical sciences', text: 'Energy flow in Earth\u2019s atmosphere can be explained by the processes of heat transfer.', keywords: ['energy', 'heat transfer', 'conduction', 'convection', 'radiation', 'atmosphere'], bloom: 'Understand' },
  { code: 'VCSSU134', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Understanding', substrand: 'Physical sciences', text: 'The motion of objects can be described and predicted using the laws of physics.', keywords: ['motion', 'newton', 'force', 'acceleration', 'velocity', 'physics law'], bloom: 'Apply' },
  { code: 'VCSIS135', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Inquiry Skills', substrand: 'Questioning and predicting', text: 'Formulate questions or hypotheses that can be investigated scientifically, including identification of independent, dependent and controlled variables.', keywords: ['hypothesis', 'variable', 'independent', 'dependent', 'controlled', 'investigation'], bloom: 'Create' },
  { code: 'VCSIS139', subject: 'science10', yearLevel: 'Year 10', strand: 'Science Inquiry Skills', substrand: 'Analysing and evaluating', text: 'Analyse patterns and trends in data, including describing relationships between variables and identifying inconsistencies.', keywords: ['data', 'pattern', 'trend', 'analyse', 'relationship', 'error'], bloom: 'Analyse' },
  // === YEAR 10 ECONOMICS & BUSINESS / ENTREPRENEURSHIP (subject=ecobiz10) ===
  { code: 'VCEBR025', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Resource Allocation and Making Choices', substrand: 'Resource allocation', text: 'Analyse the reasons why different groups have different views about the way resources should be allocated in a market economy.', keywords: ['resource', 'allocation', 'market', 'scarcity', 'opportunity cost', 'economy'], bloom: 'Analyse' },
  { code: 'VCEBC026', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Consumer and Financial Literacy', substrand: 'Consumer and financial decision making', text: 'Evaluate the effect that consumer and financial decisions can have on the individual, the broader community and the environment.', keywords: ['consumer', 'financial decision', 'budget', 'ethical', 'sustainable', 'impact'], bloom: 'Evaluate' },
  { code: 'VCEBB027', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'The Business Environment', substrand: 'Business innovation', text: 'Explain the role of innovation, including emerging technologies, in contributing to business success and its effect on consumers, business and the economy.', keywords: ['innovation', 'technology', 'startup', 'disruption', 'entrepreneurship', 'business model'], bloom: 'Understand' },
  { code: 'VCEBW028-a', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Work and Work Futures', substrand: 'Enterprising behaviour', text: 'Investigate the ways that enterprising behaviours and capabilities can be used and developed to improve the work and business environments.', keywords: ['enterprising', 'enterprise', 'initiative', 'risk', 'opportunity', 'skills'], bloom: 'Apply' },
  { code: 'VCEBE028', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Economic and Business Reasoning and Interpretation', text: 'Generate a range of viable options, taking into account multiple perspectives, use simple cost-benefit analysis to recommend and justify a course of action, and predict the intended and unintended consequences of economic and business decisions.', keywords: ['cost-benefit', 'decision', 'justify', 'consequences', 'options', 'recommend'], bloom: 'Evaluate' },
  { code: 'VCEBR024', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Resource Allocation and Making Choices', substrand: 'Economic performance', text: 'Describe how resources are allocated and distributed in the Australian economy and the way economic performance is measured.', keywords: ['GDP', 'economic performance', 'Australia', 'distribution', 'allocation', 'indicator'], bloom: 'Understand' },
  { code: 'VCEBC-START1', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Entrepreneurship (extension)', substrand: 'Value creation', text: 'Identify a customer problem, define a value proposition, and design a minimum viable product to validate assumptions.', keywords: ['customer', 'value proposition', 'MVP', 'product-market fit', 'validate', 'lean startup'], bloom: 'Create' },
  { code: 'VCEBC-START2', subject: 'ecobiz10', yearLevel: 'Year 10', strand: 'Entrepreneurship (extension)', substrand: 'Pricing and unit economics', text: 'Calculate unit economics including COGS, gross margin, customer acquisition cost and lifetime value, and justify a pricing strategy.', keywords: ['pricing', 'unit economics', 'margin', 'CAC', 'LTV', 'revenue'], bloom: 'Evaluate' },
  // === VCE PSYCHOLOGY UNIT 1 (subject=psych-u1) ===
  // AoS1: How does the brain function?
  { code: 'PSY-U1-AoS1-1', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 1', substrand: 'Role of the brain', text: 'The role of the brain in mental processes and behaviour, including the historical development of understanding of the brain and the roles of different regions.', keywords: ['brain', 'mental processes', 'behaviour', 'history', 'phrenology', 'Flourens', 'Sperry'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS1-2', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 1', substrand: 'Nervous system divisions', text: 'The divisions of the nervous system: the central nervous system (brain and spinal cord) and the peripheral nervous system (somatic and autonomic; sympathetic and parasympathetic).', keywords: ['central nervous system', 'peripheral nervous system', 'somatic', 'autonomic', 'sympathetic', 'parasympathetic', 'CNS', 'PNS'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS1-3', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 1', substrand: 'Neurons', text: 'The role of the neuron (dendrites, axon, myelin, axon terminals) as the primary functional unit of the nervous system, and the role of neurotransmitters in the transmission of neural information.', keywords: ['neuron', 'dendrite', 'axon', 'myelin', 'synapse', 'neurotransmitter', 'action potential'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS1-4', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 1', substrand: 'Brain regions', text: 'The roles of the hindbrain, midbrain and forebrain, including the cerebral cortex in integrating sensory, motor and cognitive functions.', keywords: ['hindbrain', 'midbrain', 'forebrain', 'cerebral cortex', 'frontal lobe', 'parietal', 'occipital', 'temporal'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS1-5', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 1', substrand: 'Brain plasticity', text: 'Brain plasticity and brain damage: how experience and learning can change brain structure (neuroplasticity), and how brain injury can affect biological, psychological and social functioning.', keywords: ['plasticity', 'neuroplasticity', 'brain injury', 'rehabilitation', 'stroke', 'aphasia', 'traumatic'], bloom: 'Analyse' },
  // AoS2: What influences psychological development?
  { code: 'PSY-U1-AoS2-1', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 2', substrand: 'Biopsychosocial model', text: 'The interactive influences of hereditary and environmental factors on a person\u2019s psychological development, using the biopsychosocial approach.', keywords: ['biopsychosocial', 'hereditary', 'environmental', 'nature nurture', 'development'], bloom: 'Analyse' },
  { code: 'PSY-U1-AoS2-2', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 2', substrand: 'Lifespan development', text: 'The role of sensitive and critical periods in a person\u2019s psychological development across the lifespan.', keywords: ['sensitive period', 'critical period', 'lifespan', 'attachment', 'development stage'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS2-3', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 2', substrand: 'Emotional development', text: 'The process of emotional development, including Harlow\u2019s findings and the role of attachment (Ainsworth, Bowlby).', keywords: ['attachment', 'Harlow', 'Ainsworth', 'Bowlby', 'secure', 'insecure', 'emotional'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS2-4', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 2', substrand: 'Cognitive development', text: 'Cognitive development across the lifespan with reference to the work of Piaget (sensorimotor, preoperational, concrete operational, formal operational stages).', keywords: ['Piaget', 'cognitive', 'sensorimotor', 'preoperational', 'concrete', 'formal operational', 'schema'], bloom: 'Understand' },
  { code: 'PSY-U1-AoS2-5', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 2', substrand: 'Psychological criteria of normality', text: 'The role of psychological criteria including typical and atypical behaviours, and adaptive and maladaptive behaviours, in identifying normality.', keywords: ['typical', 'atypical', 'adaptive', 'maladaptive', 'normality', 'criteria'], bloom: 'Evaluate' },
  // AoS3: Student-directed research investigation
  { code: 'PSY-U1-AoS3-1', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 3', substrand: 'Key science skills', text: 'Identification of independent, dependent and controlled variables in controlled experiments, and formulation of hypotheses that are operationalised and falsifiable.', keywords: ['variable', 'independent', 'dependent', 'controlled', 'hypothesis', 'operationalise', 'falsifiable'], bloom: 'Apply' },
  { code: 'PSY-U1-AoS3-2', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 3', substrand: 'Research methods', text: 'Investigation methodologies including controlled experiments, correlational studies, case studies, and the appropriate use of each.', keywords: ['methodology', 'experiment', 'correlation', 'case study', 'method', 'design'], bloom: 'Evaluate' },
  { code: 'PSY-U1-AoS3-3', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 3', substrand: 'Ethics', text: 'Ethical concepts and guidelines in psychological research including informed consent, confidentiality, voluntary participation, withdrawal rights, deception, debriefing, and the use of the APS code.', keywords: ['ethics', 'informed consent', 'confidentiality', 'voluntary', 'withdrawal', 'deception', 'debriefing', 'APS'], bloom: 'Evaluate' },
  { code: 'PSY-U1-AoS3-4', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 3', substrand: 'Data analysis', text: 'Use of descriptive statistics (mean, median, mode, range, standard deviation) and measures of effect to analyse and interpret data.', keywords: ['mean', 'median', 'mode', 'standard deviation', 'descriptive statistics', 'effect size'], bloom: 'Apply' },
  { code: 'PSY-U1-AoS3-5', subject: 'psych-u1', yearLevel: 'VCE Unit 1', strand: 'Area of Study 3', substrand: 'Conclusions', text: 'Drawing evidence-based conclusions, distinguishing between correlation and causation, and evaluating validity, reliability, accuracy and precision of research.', keywords: ['conclusion', 'correlation', 'causation', 'validity', 'reliability', 'accuracy', 'precision'], bloom: 'Evaluate' },
];
